/**
 * ==========================================================================
 * ギャラリーデータ (共通)
 * 画像の追加や持ち主の名前の変更はこちらで行ってください。
 * ==========================================================================
 */

const GALLERY_DATA = [
    { file: '00000.png', owner: 'Shin' },
    { file: '00001.png', owner: 'Shin' },
    { file: '00002.png', owner: 'Shin' },
    { file: '00003.png', owner: 'Shin' },
    { file: '00004.png', owner: 'Shin' },
    { file: '00005.png', owner: 'Shin' },
    { file: '00006.png', owner: 'Shin' },
    { file: '00007.png', owner: 'Shin' },
    { file: '00008.png', owner: 'Shin' },
    { file: '00009.png', owner: 'Shin' },
    { file: 'ssksgm1.png', owner: 'ssksgm' },
    { file: 'wata1.jpg', owner: 'wata' },
    { file: 'yukforest1.png', owner: 'yukforest' },
    { file: 'yukforest2.png', owner: 'yukforest' },
    { file: 'yukforest3.png', owner: 'yukforest' },
    { file: 'yukforest4.png', owner: 'yukforest' },
    { file: 'yukforest5.png', owner: 'yukforest' },
    { file: 'yukforest6.png', owner: 'yukforest' },
    { file: 'yuze_lyk1.png', owner: 'yuze_lyk' },
    { file: 'yuze_lyk2.png', owner: 'yuze_lyk' },
    { file: 'yuze_lyk3.png', owner: 'yuze_lyk' },
    { file: 'yuze_lyk4.png', owner: 'yuze_lyk' },
    { file: 'yuze_lyk5.png', owner: 'yuze_lyk' },
    { file: 'yuze_lyk6.png', owner: 'yuze_lyk' },
    { file: 'yuze_lyk7.png', owner: 'yuze_lyk' },
    { file: 'yuze_lyk8.png', owner: 'yuze_lyk' },
    { file: 'くろがね1.jpg', owner: 'くろがね' },
    { file: 'はるかず1.jpg', owner: 'はるかず' },
    { file: 'ハードコア1.jpg', owner: 'ハードコア' },
    { file: 'ハードコア2.jpg', owner: 'ハードコア' },
    { file: 'パックン1.jpg', owner: 'パックン' },
    { file: 'パックン2.jpg', owner: 'パックン' },
    { file: 'またらし1.jpg', owner: 'またらし' },
    { file: 'まちゆうこ1.png', owner: 'まちゆうこ' },
    { file: 'まちゆうこ2.png', owner: 'まちゆうこ' },
    { file: 'みけまる1.jpg', owner: 'みけまる' },
    { file: 'みけまる2.jpg', owner: 'みけまる' },
    { file: 'みけまる3.jpg', owner: 'みけまる' },
    { file: 'みけまる4.jpg', owner: 'みけまる' },
    { file: 'みけまる5.jpg', owner: 'みけまる' },
    { file: 'ルシカス1.jpg', owner: 'ルシカス' },
    { file: '可栖1.jpg', owner: '可栖' },
    { file: '可栖2.jpg', owner: '可栖' },
    { file: '可栖3.jpg', owner: '可栖' },
    { file: '可栖4.jpg', owner: '可栖' },
    { file: '可栖5.jpg', owner: '可栖' },
    { file: '可栖6.jpg', owner: '可栖' },
    { file: '可栖7.jpg', owner: '可栖' },
    { file: '可栖8.jpg', owner: '可栖' },
    { file: '可栖9.jpg', owner: '可栖' },
    { file: '可栖10.jpg', owner: '可栖' },
    { file: '可栖11.jpg', owner: '可栖' },
    { file: '可栖12.jpg', owner: '可栖' },
    { file: '可栖13.jpg', owner: '可栖' },
    { file: '可栖14.jpg', owner: '可栖' },
    { file: '可栖15.jpg', owner: '可栖' },
    { file: '可栖16.jpg', owner: '可栖' },
    { file: '可栖17.jpg', owner: '可栖' },
    { file: '常に眠たい人1.jpg', owner: '常に眠たい人' },
    { file: '母音1.jpg', owner: '母音' },
    { file: '髙橋1.jpg', owner: '髙橋' }
];
